#!/usr/bin/env python3
"""Generates Shared/DailyVerses.swift from the bundled Quran data.

The verse text is copied verbatim from the bundled files (Tanzil Uthmani text
and the ClearQuran translation), as both licences require. Edit CANDIDATES to
change which verses appear in the "Verse of the Day" widget, then re-run:

    python3 scripts/generate_daily_verses.py
"""
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
QURAN = ROOT / "Salah/Resources/Quran"
OUT = ROOT / "Shared/DailyVerses.swift"

CANDIDATES = [
    (2, 45), (2, 152), (2, 153), (2, 186), (2, 201), (2, 238), (2, 286),
    (3, 8), (3, 139), (3, 173), (3, 200), (7, 23), (11, 114), (13, 28),
    (14, 7), (14, 40), (17, 80), (20, 14), (20, 114), (21, 87), (25, 63),
    (28, 24), (29, 45), (29, 69), (33, 41), (39, 53), (40, 60), (50, 16),
    (55, 13), (57, 4), (62, 10), (64, 16), (65, 3), (67, 2), (73, 8),
    (87, 14), (93, 5), (94, 5), (94, 6), (103, 3), (112, 1),
]
MAX_ENGLISH = 170

def swift_string(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'

def main() -> None:
    arabic = json.loads((QURAN / "quran-uthmani.json").read_text("utf-8"))
    english = json.loads((QURAN / "translation-en-clearquran.json").read_text("utf-8"))
    chapters = {c["id"]: c for c in json.loads((QURAN / "chapters.json").read_text("utf-8"))["chapters"]}
    lines = []
    for surah, ayah in CANDIDATES:
        ar = arabic[str(surah)][ayah - 1]
        en = english[str(surah)][ayah - 1]
        assert ar["verse"] == ayah and en["verse"] == ayah
        if len(en["text"]) > MAX_ENGLISH:
            continue
        name = chapters[surah]["transliteration"]
        lines.append(
            f"        DailyVerse(surah: {surah}, ayah: {ayah}, surahName: {swift_string(name)},\n"
            f"                   arabic: {swift_string(ar['text'])},\n"
            f"                   english: {swift_string(en['text'])}),"
        )
    OUT.write_text(
        "// GENERATED by scripts/generate_daily_verses.py — do not edit by hand.\n"
        "// Arabic: Tanzil Uthmani text (CC BY 3.0, verbatim). English: Talal Itani, ClearQuran.com (CC BY-ND 4.0).\n\n"
        "import Foundation\n\n"
        "struct DailyVerse: Hashable {\n"
        "    let surah: Int\n    let ayah: Int\n    let surahName: String\n    let arabic: String\n    let english: String\n\n"
        "    var reference: String { \"\\(surahName) \\(surah):\\(ayah)\" }\n\n"
        "    /// The same verse for everyone on a given calendar day.\n"
        "    static func forDay(_ date: Date, calendar: Calendar = .current) -> DailyVerse {\n"
        "        let day = calendar.ordinality(of: .day, in: .era, for: date) ?? 0\n"
        "        return all[day % all.count]\n"
        "    }\n\n"
        "    static let all: [DailyVerse] = [\n" + "\n".join(lines) + "\n    ]\n}\n",
        "utf-8",
    )
    print(f"Wrote {len(lines)} verses to {OUT.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
